language: python
cache: pip
sudo: false

python:
  - "3.6"
  - "2.7"

branches:
  only:
    - master
    
install:
  - if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]]; then pip install --upgrade sphinx sphinx-sitemap; fi
  - pip install --upgrade pytest pytest-pep8 pytest-cov pytest-mock codecov
  - pip install .

script:
  - pytest -v --cov MDAnalysisData MDAnalysisData 

after_success:
  # only need to build docs on 3.6 version
  # touch .nojekyll else github-pages messes up theme
  - if [[ $TRAVIS_PYTHON_VERSION == "3.6" ]]; then python setup.py build_sphinx && touch ./build/sphinx/html/.nojekyll; fi
  - codecov

deploy:
  # stuff related to deploying to gh-pages
  # GITHUB_TOKEN is set in Travis-CI settings (@orbeckst)
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
    python: "3.6"
  local_dir: build/sphinx/html
  project_name: MDAnalysisData
