name: Build and upload to PyPi

on:
  push:
    tags:
      - "*"
  release:
    types:
      - published

jobs:
  pypi_push:
    environment: deploy
    if: "github.repository == 'MDAnalysis/MDAnalysisData'"
    name: Build, upload and test pure Python wheels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: testpypi_deploy
        uses: MDAnalysis/pypi-deployment@main
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        with:
          test_submission: true
          package_name: MDAnalysisData
          module_name: 'MDAnalysisData'

      - name: pypi_deploy
        uses: MDAnalysis/pypi-deployment@main
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          package_name: MDAnalysisData
          module_name: 'MDAnalysisData'
