name: docs deployment
on:
  push:
    branches:
      - master

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  docs:
    if: github.repository == 'MDAnalysis/MDAnalysisData'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install sphinx, pytest, pytest plugins
      run: |
        python -m pip install wheel
        python -m pip install pytest pytest-cov pytest-pep8 pytest-mock codecov
        python -m pip install sphinx sphinx-sitemap sphinx-rtd-theme

    - name: Install main dependencies
      run: |
        python -m pip install six setuptools tqdm

    - name: install package
      run: |
        pip install -v .

    - name: build docs
      run: |
        python setup.py build_sphinx

    - name: deploy docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/sphinx/html
        user_name: 'github-actions'
        user_email: 'github-action@users.noreply.github.com'
