name: GH Actions CI

on:
  # run every Sunday at 3:53 UTC
  schedule:
    - cron: "53 3 * * 0"
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

concurrency:
  group: "${{ github.ref }}-${{ github.head_ref }}"
  cancel-in-progress: true

jobs:
  unittests:
    name: Test ${{ matrix.os }} with Python ${{ matrix.python-version }}
    if: github.repository == 'MDAnalysis/MDAnalysisData'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        include:
          - os: macOS-latest
            python-version: 2.7	
          - os: macOS-latest
            python-version: 3.9
          - os: windows-latest
            python-version: 2.7	
          - os: windows-latest
            python-version: 3.9

    steps:
    - uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Display Python version
      run: python -c "import sys; print(sys.version)"

    - name: Install testing dependencies (pytest, pytest plugins)
      run: |
        python -m pip install wheel
        python -m pip install pytest pytest-cov pytest-pep8 pytest-mock codecov

    - name: Install package dependencies
      run: |
        python -m pip install six setuptools tqdm

    - name: Install compatibility dependencies for Python 2.7 only
      if: startsWith(matrix.python-version, '2.7')
      run: python -m pip install pathlib2 

    - name: Install package
      run: |
        python -m pip install -e .

    - name: Run tests
      run: |
        pytest -v --cov=MDAnalysisData --cov-report=xml --color=yes MDAnalysisData/tests

    - name: Codecov
      uses: codecov/codecov-action@v2
      with:
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
        file: ./coverage.xml
        fail_ci_if_error: True
        verbose: True
